[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prac"
version = "0.1.0"
description = "Some leetcode questions and answers"
authors = [
    { name="adam jensen" }
]
dependencies = []

[tool.setuptools.packages.find]
where = ["source"]

